Adds "AFTER" constraint at createColumnConstraint
db-migrate/mysql pull request #29
Opened 2021-04-22 18:45 UTC by FabioBachi

2021-04-23 09:48 UTC, wzrdtales requested changes
in general ok just my comments and the missing requirement of a test for this new functionality

2021-04-23 09:48 UTC, wzrdtales commented on index.js
> +      constraints: [escapedName, t, len, constraint.constraints].join(' '),
please comfort your auto fixer with db-migrates internal rules:

https://github.com/db-migrate/mysql/blob/master/.prettierrc
https://github.com/db-migrate/mysql/blob/master/.eslintrc

trailing commas are not part of this for example.

2021-04-23 10:25 UTC, wzrdtales commented
there are now proper githooks in place, please sync with the master branch and install the dependencies

2021-04-23 15:11 UTC, FabioBachi commented
> in general ok just my comments and the missing requirement of a test for this new functionality

Hi! I have just mande the changes and updated a test to validate this new feature.

2021-04-23 15:32 UTC, wzrdtales approved these changes

2021-04-23 15:32 UTC, wzrdtales commented
thank you for your contribution :tada: !

2021-04-23 15:32 UTC, merged

2021-05-18 10:08 UTC, mjfold commented
Hey @wzrdtales when can we expect this to get an npm release?

2021-08-03 13:42 UTC, wirdehall commented
> Hey @wzrdtales when can we expect this to get an npm release?

I would also like to know this. Can we get any news about when the next release is planed? :)

2021-09-21 07:42 UTC, wzrdtales commented
sorry this got under the radar again version comes today